### ISSUE TITLE
Monitor crashes on Stats tab using the `min.js` file.

### ISSUE THREAD

**Issue by sarahcstringer** [twilio/twilio-video-room-monitor.js#38]
I'm testing out the Video Room Monitor and using it by pulling the `twilio-video-room-monitor.min.js` file directly into my web app and loading it with a <script> tag. The monitor appears and I can see everything on the Info tab, but when I try to load the Stats tab, it crashes (the whole monitor disappears -- stack trace below).

<img width="1437" alt="Screen Shot 2021-09-30 at 8 02 36 AM" src="https://user-images.githubusercontent.com/13165465/135485746-5a573c3d-393e-43f2-9372-50972dc01b62.png">

When I use the regular `.js` file instead of the `min.js` file, everything works and I can use the Stats tab.

I downloaded the room monitor files with `npm install` and am using the `1.0.0-beta.1` version.

**Comment by olipyskoty** [comment]
@sarahcstringer thank you for the bug report!

We were able to reproduce this issue and fixed it by upgrading the package `parcel-bundler` to `parcel 2.0.0`. You can check out this PR #40 for more info!

**Comment by Chigsy** [comment]
Was this confirmed to be fixed @sarahcstringer?

I'm still seeing this issue (or a very close one) on my end. I confirmed that im on v1.0.0 and I do see that parcel is set to 2.0.0 in the dev dependencies of the package. I get the first error on load of the video monitor and the similar missing function errors + a crash when clicking the Stats tab. See below screenshot (difference being it looks like its a different set of similar functions missing):

<img width="649" alt="Screen Shot 2021-12-19 at 10 31 19 AM" src="https://user-images.githubusercontent.com/3409216/146680897-f46d030a-e4d4-4f71-b62b-05a1f1a4dae5.png">

**Comment by olipyskoty** [comment]
Hey @Chigsy thanks for reaching out!

I just tried to reproduce the issue and was unable to do so. Here are the steps that I took:

1. Cloned the repo
2. Ran `npm i` in the terminal
3. Ran `npm run build` in the terminal
4. Copied the `twilio-video-room-monitor.min.js` file from the `dist/browser` directory and added it to my video web app
5. Added `<script src='/twilio-video-room-monitor.min.js'></script>` to the `index.html` file in my web app (note, my minified file was in the same directory as my `index.html` file. You'll need to include the exact path to the minified file in your own web app.)
6. Started my video app and ran the following in the browser console:
```
window.Twilio.VideoRoomMonitor.registerVideoRoom(room);
window.Twilio.VideoRoomMonitor.openMonitor();
```
7. Opened the Stats tab without error. 
**Note**, the `Error: <path> attribute d...` is a known error and should not have any noticeable impact on the Video Monitor's functionality.

Do you mind replying to this issue with the information below? This will help us reproduce your issue and understand where the error is coming from:

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Browser: [e.g. Chrome 80, Firefox 72]
 - App Version: [e.g. 0.1.0]
 - SDK Version: [e.g 2.1.0]
 - Node.js version: [e.g. 12.14.1]

**Additional context**
Add any other context about the problem here.

Thank you and have a happy new year!
